version: '2'

services:
  mysql-ipam:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    restart: always
    ports:
      - "3333:3306"
    volumes:
      - db_data:/var/lib/mysql
  ipam:
    depends_on:
      - mysql-ipam
    image: pierrecdn/phpipam
    environment:
      - MYSQL_ENV_MYSQL_USER=root
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_ENV_MYSQL_HOST=mysql
    ports:
      - "8123:80"
volumes:
  db_data:
